# Known CPUs

# Intel Client CPUs
#  Haswell
- architecture: HSW
  family: 6
  models:
  - 50
  - 69
  - 70
  minstepping: "0"
  maxstepping: "0"
  channels: 2

#  Broadwell
- architecture: BDW
  family: 6
  models:
  - 61
  - 71
  minstepping: "0"
  maxstepping: "0"
  channels: 2

#  Skylake
- architecture: SKL
  family: 6
  models:
  - 78
  - 94
  minstepping: "0"
  maxstepping: "0"
  channels: 2

#  Kabylake
- architecture: KBL
  family: 6
  models:
  - 142
  - 158
  minstepping: "9"
  maxstepping: "9"
  channels: 2

#  Coffelake
- architecture: CFL
  family: 6
  models:
  - 142
  - 158
  minstepping: "10"
  maxstepping: "13"
  channels: 2

#  Rocket Lake
- architecture: RKL
  family: 6
  models:
  - 167
  minstepping: "0"
  maxstepping: "0"
  channels: 2

#  Tiger Lake
- architecture: TGL
  family: 6
  models:
  - 140
  - 141
  minstepping: "0"
  maxstepping: "0"
  channels: 2

#  Alder Lake
- architecture: ADL
  family: 6
  models:
  - 151
  - 154
  minstepping: "0"
  maxstepping: "0"
  channels: 2

# Intel Xeon Server CPUs
#  Haswell
- architecture: HSX
  family: 6
  models:
  - 63
  minstepping: "0"
  maxstepping: "0"
  channels: 4

#  Broadwell
- architecture: BDX
  family: 6
  models:
  - 79
  - 86
  minstepping: "0"
  maxstepping: "0"
  channels: 4

#  Skylake
- architecture: SKX
  family: 6
  models:
  - 85
  minstepping: "0"
  maxstepping: "4"
  channels: 6

#  Cascadelake
- architecture: CLX
  family: 6
  models:
  - 85
  minstepping: "5"
  maxstepping: "7"
  channels: 6

#  Cooperlake
- architecture: CPX
  family: 6
  models:
  - 85
  minstepping: "11"
  maxstepping: "11"
  channels: 6

#  Icelake
- architecture: ICX
  family: 6
  models:
  - 106
  - 108
  minstepping: "0"
  maxstepping: "0"
  channels: 8

#  Sapphire Rapids
- architecture: SPR
  family: 6
  models:
  - 143
  minstepping: "0"
  maxstepping: "7"
  channels: 8

#  Emerald Rapids
- architecture: EMR
  family: 6
  models:
  - 143
  minstepping: "8"
  maxstepping: "8"
  channels: 8
